version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: undangan-app
        depends_on:
            - db
        networks:
            - undangan
        env_file:
            - .env

    db:
        image: postgres:latest
        container_name: undangan-db
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - undangan

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: undangan-nginx
        ports:
            - 10000:80
        networks:
            - undangan
        depends_on:
            - app

volumes:
    postgres_data:

networks:
    undangan:
        driver: bridge
